deploy:
  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Replace with your desired region

    - name: Deploy to AWS with SST
      run: npx sst deploy --stage prod
